### ISSUE TITLE
Rename ml-matrics to pymatviz

### ISSUE THREAD

**Issue by janosh** [janosh/ml-matrics#21]
Not entirely happy with the name `ml-matrics` anymore. Thinking of changing it to `mainvis` for **ma**terials **in**formatics **vis**ualizations. Not sure if it's really better but at least seems to more correctly represent the current focus of this package.

Let me know if you think the new name is terrible @CompRhys @sgbaird. Otherwise will change the name next week maybe.

**Comment by sgbaird** [comment]
Seems like a good shift. In terms of Google searches, it looks like it mostly pulls up people with the last name of mainvis. Doesn't seem to have name conflicts or confusions in materials informatics or on GitHub. I hadn't thought of using main as an abbreviation for materials informatics. Something about MaInVis (with the capital letters) strikes me as odd, so all lowercase seems better as you have it. Maybe because the i can be mistaken as an l, and In looks like Indium. MainVis doesn't seem necessary since main and vis read pretty separately in mainvis.

matVis pulls up as a MATLAB package. vismat seems to be a software file extension. vismi or vizmi (i.e. visualizations for materials informatics) would be competing with visme (infographics website) to some extent, but sounds a bit catchy.

Overall I think `mainvis` is nice, and as a side note I'll be considering the use of "main" for "materials informatics" in other packages; I don't have much claim to package naming creativity 😅

**Comment by sgbaird** [comment]
pymatvis or pymatviz also comes to mind, but if pymatgen isn't a dependency, then people might get confused.

**Comment by janosh** [comment]
Lots of good points! Thanks guys.

> vismi or vizmi (i.e. visualizations for materials informatics) would be competing with visme (infographics website) to some extent, but sounds a bit catchy.

Maybe catchy but sounds cool. 😄

> pymatvis or pymatviz also come to mind, but if pymatgen isn't a dependency (EDIT: looks like it is) or people can't use e.g. Composition or esp. Structure objects, then people might get confused.

It's definitely meant to be part of the pymatgen ecosystem. I considered `pymatviz` too a while back but thought it too copy-cat. But considering it signals very clearly the goal of being compatible and a useful addon, maybe the unoriginal name is fine.

> I don't have much claim to package naming creativity 😅

Me neither. 😄

> as a side note I'll be considering the use of "main" for "materials informatics" in other packages; 

All yours!

**Comment by janosh** [comment]
@sgbaird Thanks again for your input. We're going with `pymatviz` with permission from @shyuep himself (who says he'll become a user btw)! 😅
